### ISSUE TITLE
Session 6 Playground (with Delegate Example)

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/MPCS51030-2017-Winter-Forum#100]
I added a new playground for Session 6 ( https://github.com/uchicago-mobi/mpcs51030-2017-winter-playgrounds) that shows some useful techniques for the assignment:
* Stripping HTML tags from a String (3 different ways)
* Using `UserDefaults`.  Warning: `UserDefaults` does not work in Playgrounds, but the code is valid.
* An example of declaring and using a custom protocol and delegate to communicate between a view and a view controller.  I hope this clarifies the pattern.  Also, check out #99 for a link to a post on delegates.

**Comment by lakshman111** [comment]
I downloaded the new playground, but it looks like only the first two bullets are covered in there (the third bullet is missing?)
![screenshot 2017-02-15 19 56 07](https://cloud.githubusercontent.com/assets/4174501/23003831/dc55343c-f3b8-11e6-95b9-26f75ee9a442.png)

**Comment by tabinks** [comment]
@lakshman111 You may have downloaded the playground before I updated with the delegate example.  Pull it again and see if its there.
