### ISSUE TITLE
Issue parsing JSON into a dictionary

### ISSUE THREAD

**Issue by ijl0322** [uchicago-mobi/MPCS51030-2017-Winter-Forum#102]
Has anyone else encounter issues when trying to parse JSON from the Duck Duck Go API to dictionaries ?? 

I used the following code, which was exactly the same as the one I used for the Github homework. 

 let json = try JSONSerialization.jsonObject(with: data, options: .allowFragments)
 print("\(json)") \n

guard let issues = json as? [[String: AnyObject]] else {
                    fatalError("We couldn't cast the JSON to an array of dictionaries")
}

This gets the JSON file but failed to parse it into a dictionary. 

![image](https://cloud.githubusercontent.com/assets/15901531/22985781/295ebd38-f36f-11e6-8aeb-2ea5549e73b2.png)

I tried replacing the Duck Duck go Url with the github issue url, and all works as expected. I'm not very familiar with JSON, but I'm thinking the ones from Duck Duck Go is formatted differently or something ??? 

Thanks!

**Comment by tabinks** [comment]
Can you post the exact URL you used here?  First thing to check is if there is a problem with the results being returned?  

JSON is a flexible structured data format, which means that it can be structured however a developer wants.  The JSON from one API won't match the JSON from another.  You will need to inspect it to figure out how the data is being passed.  For example, Issues was an array of dictionaries.  That doesn't mean that DuckDuckGo will be the same.

**Comment by tabinks** [comment]
Also, there are some browser extensions that allow you to view JSON in a pretty format (spaces, indents, newlines).  This can be very useful for parsing.

**Comment by ijl0322** [comment]
I see, I assumed that JSON are structured the same way and should always be parsed the same way. It's working as it should now! Thanks!
