### ISSUE TITLE
Previous builds not working on iPhone

### ISSUE THREAD

**Issue by lakshman111** [uchicago-mobi/MPCS51030-2017-Winter-Forum#103]
I put every project that we make on my iPhone.  I have noticed that over time, the builds crash and then I need to re-run them through xcode to get them working on my phone again.  Are apps that are run through xcode only temporarily stored when run on an iPhone?

**Comment by hbennett766** [comment]
No, an app you install via xcode works like any other app you'd download from the app store. It's just there forever until you delete it. My best guess is there's a bug somewhere in your code that's crashing the app. For whatever reason, this crash bug in particular isn't resolved until you build again via xcode.

**Comment by tabinks** [comment]
We discussed this in office hours.
