### ISSUE TITLE
SharedNetworkingClass

### ISSUE THREAD

**Issue by turabhassan89** [uchicago-mobi/MPCS51030-2017-Winter-Forum#105]
which class should the the sharedNetworkingClass inherit from?

**Comment by susanstevens** [comment]
It does not need to inherit from another class.

**Comment by tabinks** [comment]
It should be a native Swift class.  It doesn't need to inherit from anything.

If you are confused from seeing examples online that might have inherited from `NSObject`, this was the old way of setting up a singleton.  Swift greatly simplified the pattern.
