### ISSUE TITLE
bookmark clarification

### ISSUE THREAD

**Issue by ramon-luis** [uchicago-mobi/MPCS51030-2017-Winter-Forum#106]
Can you clarify which should be saved to bookmarks:
1. - the current URL in the webview (regardless of how the user arrived at the website)
2. - the original URL that was loaded when the user clicked in the master table

I currently am saving the original URL and search term, but a user could click through several links to be on an entirely different website when they click the bookmark button.

**Comment by susanstevens** [comment]
Good question. For this assignment, it's fine to save the original URL (from the search results in the master view controller).

**Comment by tabinks** [comment]
Yes, just save the initial URL from the search.
