### ISSUE TITLE
requirement checklist

### ISSUE THREAD

**Issue by ramon-luis** [uchicago-mobi/MPCS51030-2017-Winter-Forum#107]
I noticed that for some of my projects the grader used a checklist to evaluate the project.  Would it be possible to get a similar checklist for the current assignment?

The format of the assignment description is very instructive, but it is easy to accidentally miss required features.  It would be helpful to have the same grading rubric available to make sure we're not missing anything.

Thanks!

**Comment by susanstevens** [comment]
We don't typically provide a checklist. Personally, I think it's good practice to have to read through the instructions and make sure that you've understood all of the requirements. This is something software developers have to do every day. Of course, you should always post here if you're unsure about something.

@tabinks any thoughts on this one?

**Comment by tabinks** [comment]
I agree with @susanstevens.  Being able to read through an app specification and break it down in to tasks is an important part of software development.
