### ISSUE TITLE
Make-up Class Schedule

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/MPCS51030-2017-Winter-Forum#108]
We will have a makeup class this Saturday from 9-11.  There will be office hours immediately after with Susan, Paul and myself from 11-12.  

Please note, class will be in **Young 302**.

**Comment by tabinks** [comment]
I know that some students have trouble with their IDs not working to gain access to the building.  If you get locked out send an Issue and we will send someone down to let you in.

**Comment by gglotze** [comment]
I'm downstairs right now and it's not letting me in unfortunately
