### ISSUE TITLE
Bookmarks implementation

### ISSUE THREAD

**Issue by bygong** [uchicago-mobi/MPCS51030-2017-Winter-Forum#109]
Hi, it is said the bookmark tableview should be editable. Would you expect to to have a navigation bar and its item to do that, or just fair enough to make cells editable?

**Comment by alexliu0809** [comment]
I think it refers to allow users to delete articles from the list, which could be done by overwriting a few functions

**Comment by susanstevens** [comment]
The instructions don't explicitly say that you need an edit button to enable editing on your bookmark tableview, but in my opinion it would be best practice to provide one (either in a navigation bar, or wherever makes sense to you). The alternative that is just to enable swipe-to-delete, with no visual cue to the user that the gesture is available to them. iOS makes it easy to enable editing mode on a table (using an edit button) AND to implement swipe-to-delete. So my advice would be to give your users both options.

On a related note, here's an interesting [article](https://www.nngroup.com/articles/contextual-swipe/?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=email&utm_source=iOS_Dev_Weekly_Issue_288) on some of the pitfalls of swipe-to-delete.

**Comment by tabinks** [comment]
Yes, the exact implementation is up to you.  You would be amazed at how many people never think to swipe anything.  It's may be a generational thing 🤷‍♂️.
