### ISSUE TITLE
Link on Final Slide Broken

### ISSUE THREAD

**Issue by lakshman111** [uchicago-mobi/MPCS51030-2017-Winter-Forum#11]
The video link in the final slide from lecture 1 doesn't work (http://uchicago.mobi/courses/bootcamp/tutorials.html).  Can someone provide a working link to that video?

**Comment by tabinks** [comment]
I accidentally included some slides from previous years.  The slides after "The End" are outdated.  Please ignore them.  I have updated the link with the correct slides.
