### ISSUE TITLE
hw1 not graded

### ISSUE THREAD

**Issue by c439621258** [uchicago-mobi/MPCS51030-2017-Winter-Forum#111]
I have just found that my assignment one has not been graded.
That might be due to my late reply to the google form about my account information, but I have commit my code in time (which can be shown by the commit time)

Can anyone grade my assignment 1 ?
Sorry for any inconvenience I made.

Here is the address of my repository of my hw1:
https://github.com/uchicago-mobi/mpcs51030-2017-winter-assignment-1-c439621258

**Comment by ijl0322** [comment]
It might possibly be on the grade branch. I have also thought my hw 1 is not graded for quite a while.

**Comment by susanstevens** [comment]
@c439621258 You're right, it doesn't look like you have a grade for assignment 1. I'll grade it today. Thanks for letting us know!

**Comment by c439621258** [comment]
@susanstevens Thanks for your work!
