### ISSUE TITLE
Custom camera view advice

### ISSUE THREAD

**Issue by taburaad** [uchicago-mobi/MPCS51030-2017-Winter-Forum#115]
Hi, 

Unrelated to this week's HW, but I was wondering if anyone has good resources/tutorial links to making a custom camera view in Swift 3/iOS 10.2. I'm asking because I've found good ones for previous Swift/iOS versions that don't work for the current ones due to updates. 

Thanks,
Tony

**Comment by susanstevens** [comment]
Have you looked at [this tutorial](https://makeapppie.com/2016/06/28/how-to-use-uiimagepickercontroller-for-a-camera-and-photo-library-in-swift-3-0/)? It uses Swift 3 and it looks like it's pretty thorough. It does mention that you need to test on a real device (not the simulator) to get the camera working.
