### ISSUE TITLE
SharedNetworking guidelines

### ISSUE THREAD

**Issue by aaggarw99** [uchicago-mobi/MPCS51030-2017-Winter-Forum#117]
Hello,

Does anyone have a good tutorial for dataTask completion handlers in singletons? My JSON parsing method does not run 
`URLSession.shared.dataTask(with: url, completionHandler: { (data, response, error) -> Void in` 
The homework suggests that the completion handler parameters would be different and that the class will return a value. Not quite sure what this means / why completion handlers are defined differently for singletons. 

Some other notes:
- I am resuming the task at the end
- Since the program is skipping this task essentially, I can't really optimize the debugger

Thanks

**Comment by tabinks** [comment]
There is a working example in the Playgrounds repository.

**Comment by aaggarw99** [comment]
I looked at the examples in the repository but still don't understand why my completion handler isn't being called when I create a new task in the singleton. It works fine when I place my parseJSON method in my MasterViewController; the singleton, however, just won't run it.
