### ISSUE TITLE
UIWebView vs WKWebView

### ISSUE THREAD

**Issue by hbennett766** [uchicago-mobi/MPCS51030-2017-Winter-Forum#118]
Good question by @jahnagoldman on UIWebView vs WKWebView as a part of #104: "I noticed when you look at the API reference (https://developer.apple.com/reference/uikit/uiwebview and https://developer.apple.com/reference/webkit/wkwebview) it seems to say to use WKWebView instead of UIWebView in iOS 8 and later - is it ok to use either one then? My app had the issue mentioned above until I tried using the WKWebView, which seemed to work well."

The use cases of UIWebView and WKWebView are pretty much the same. They both provide in-app web functionality. Apple has been pushing WKWebView in iOS 8 and newer for performance reasons, as best explained in the last link below, but UIWebView has not been deprecated or replaced by it.

Official Apple documentation:

[WKWebView](https://developer.apple.com/reference/webkit/wkwebview)
[UIWebView](https://developer.apple.com/reference/uikit/uiwebview)

Why Introduce WKWebView?

[Short Answer](https://www.hackingwithswift.com/example-code/wkwebview/whats-the-difference-between-uiwebview-and-wkwebview)
[Longer Answer + Tutorial on Implementation (Obj-C)](http://arsenkin.com/WKWebView-the-time-has-come-to-ditch-UIWebView.html)
[Longest But Most Thorough Answer](https://www.macstories.net/stories/ios-9-and-safari-view-controller-the-future-of-web-views/)

**Comment by tabinks** [comment]
@jahnagoldman Great question and great answer. @hbennett766 

You can chalk my endorsement of `UIWebView` to being old and resistant to change.  For this assignment, use whichever you want.  In the future I will require `WKWebView`.  There are too many advantages to ignore.
