### ISSUE TITLE
Favorite Bookmark

### ISSUE THREAD

**Issue by alexliu0809** [uchicago-mobi/MPCS51030-2017-Winter-Forum#119]
Question on a special case.
Suppose user opens the bookmark list from a webpage, and the webpage is in the list.
(So now there should be a star on the detail view before opening the bookmark list)
Then user deletes the current page from the bookmark list and closes the bookmark list.
(Now we return to  the detail view page)
Do we need to remove the star from detail view too? Or can we keep the star until user reloads it?

**Comment by tabinks** [comment]
If you were going to put this in the App Store, then I would remove it.  However, for this assignment, it is fine to leave it until the web view reloads.  

These kind of "special cases" are all the little details that always take longer than you anticipate.  Its good that you noticed that.
