### ISSUE TITLE
Having trouble uploading the folder to my repository

### ISSUE THREAD

**Issue by Victoriatheeast** [uchicago-mobi/MPCS51030-2017-Winter-Forum#12]
Hey,

I am having trouble uploading the FoodTracker folder to my assignment 1 repository. After I committed and pushed back all the changes, the folder is empty as shown on my git hub page, but the playground works.

Thank you!
Victoria

**Comment by CocoCui** [comment]
Xcode created a local repo. Just delete the .git folder in FoodTrack and push again.
```
cd FoodTracker
rm -rf .git
```

**Comment by Victoriatheeast** [comment]
Thank you! I tried, but still it was saying "everything up-to-date".

**Comment by CocoCui** [comment]
just try
```
cd repo
git add .
git commit -m "message"
git push -u origin master
```

**Comment by Victoriatheeast** [comment]
Well, I still got : 
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

**Comment by CocoCui** [comment]
Maybe remove the FoodTacker, git commit and push, and then add the FoodTracker back will work

**Comment by Victoriatheeast** [comment]
Finally it works. I ended up removing the submodules, and then add it back as folders, which is same thing as you mentioned before. Thank you!
