### ISSUE TITLE
Use dataSource / reloadData to populate table that is jumping the gun?

### ISSUE THREAD

**Issue by ghost** [uchicago-mobi/MPCS51030-2017-Winter-Forum#121]
Hello-
My problem appears to be that my table loads before the data is available. I have it printing the results of the first tableView function and also the formatted query results once I have them, but it prints 0, then the query results.

I've found some things saying to set dataSource to nil until the data is available, then call reloadData, but I can't find an example of this and I'm not sure where dataSource is should be assigned / reassigned and what reloadData is called on.

**Comment by tabinks** [comment]
The typical flow would be:
* load a view controller with a table (possibly done in storyboard)
* Start loading the data in `viewWillAppear` (this assumed it is loading in the background)
* Reload table after the data is downloaded and processed in a completion block (don't forget to call it on the main thread).

In my experience, you shouldn't need to explicitly the source to `nil`.  The data source can be set, but empty (as sounds like is your case).  If the array holding the data is empty, then it just won't show any data until the array is full and the `reloadTable` is called.
