### ISSUE TITLE
Clarification on Final Project Proposals

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/MPCS51030-2017-Winter-Forum#122]
Please don't forget to include a ~1 page summary of your proposed application.  Include a rough "Storyboard" of all the major view controllers.  It is fine to hand draw it, take a picture and embed in the document.

### Please covert the final document to a .pdf ###

**Comment by lakshman111** [comment]
Where do we turn this in?

**Comment by mengwanguc** [comment]
If we choose to work in a team, how many proposals should we turn in? Should only one member or both members in our team turn in the proposal?

**Comment by kirinm** [comment]
Should we upload the final project proposal PDF to GitHub?
