### ISSUE TITLE
Indicator

### ISSUE THREAD

**Issue by alexliu0809** [uchicago-mobi/MPCS51030-2017-Winter-Forum#123]
How can we display network indicator in masterview? 
How can we add UIActivityIndicator to master view?

**Comment by susanstevens** [comment]
The network activity indicator is the small spinner you see in the status bar at the top of your device or simulator (in line with the time). Try just setting `isNetworkActivityIndicatorVisible = true` and removing or commenting out the line where you set it to be false. You should see it spinning.

**Comment by alexliu0809** [comment]
Thx. I already set NetworkActivityIndicatorVisible in masterview. But I still wonder do we need to add UIActivityIndicator (which is in the center of the screen) to masterview?

**Comment by susanstevens** [comment]
The UIActivityIndicator only needs to appear when the web view is loading content. It should be centered on the detail view. The network activity indicator should appear whenever there is network activity (on master or detail).

**Comment by alexliu0809** [comment]
Thx.
