### ISSUE TITLE
Bookmark System Bar Handling

### ISSUE THREAD

**Issue by ptnsv** [uchicago-mobi/MPCS51030-2017-Winter-Forum#124]
Hello,

For the following requirement:

"Add a UIBarButton to the navigation bar that has a segue to a BookmarkViewController. This segue should of type Present As Popover and can be set in the Storyboard.

Tip: You can use the system bar item Bookmark icon or a custom image."

When handling this, do we just need to show the popover with all bookmarks? Or do we also need to save the currently loaded link as  a bookmark?

Thank you.

**Comment by susanstevens** [comment]
You should show all of the favorites the user has saved. The user can open the popover while viewing a website they haven't favorited, in which case the current URL won't appear in the popover.
