### ISSUE TITLE
Change Theme using UIAppearance

### ISSUE THREAD

**Issue by alexliu0809** [uchicago-mobi/MPCS51030-2017-Winter-Forum#125]
Hi, I have a static function for changing appearance.
static func setTo()
    {
        UINavigationBar.appearance().tintColor = UIColor.orange
    }
But it only works when the view is first loaded.
I call this function when a button is tapped and does not have any effect. 
My code is in my repo and I would appreciate it if someone could have a look at it. thx

**Comment by susanstevens** [comment]
From the UIAppearance documentation: "iOS applies appearance changes when a view enters a window, it doesn’t change the appearance of a view that’s already in a window. To change the appearance of a view that’s currently in a window, remove the view from the view hierarchy and then put it back."

It sounds like you are trying to change the appearance of a view that's already in a window (i.e., already on screen). You don't need to do that for this assignment.

**Comment by alexliu0809** [comment]
Ok. Thanks a lot
