### ISSUE TITLE
PLBuildVersion Bug

### ISSUE THREAD

**Issue by cszc** [uchicago-mobi/MPCS51030-2017-Winter-Forum#126]
Is anyone else getting this warning?

> Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x126cd0998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x126af2880). One of the two will be used. Which one is undefined.

My app crashes after it loads the UIWebView. I tried following the instructions here:
http://stackoverflow.com/questions/39520499/class-plbuildversion-is-implemented-in-both-frameworks

But no luck. Anyone else have the same issue?

**Comment by cszc** [comment]
Update: I get the error when I try adding the activity indicator to my detail page. It works if I comment this code out:

```
        activityIndicator.center = self.view.center
        activityIndicator.hidesWhenStopped = true
        activityIndicator.activityIndicatorViewStyle = UIActivityIndicatorViewStyle.gray
        view.addSubview(activityIndicator)
        
        activityIndicator.startAnimating()
```

**Comment by bgharper** [comment]
I got the exact same warning, but it never crashes for me (I don't have an iPhone so I've been testing in XCode). It looks like a somewhat mysterious UIWebView bug.
