### ISSUE TITLE
URL Session keep loading data when Internet is cut down

### ISSUE THREAD

**Issue by mengwanguc** [uchicago-mobi/MPCS51030-2017-Winter-Forum#127]
When I turned off the wifi and test the search function of my program, the urlSession just keeps doing dataTask and never stops. No error is detected. I noticed that the completionHandler is never called. Maybe it never completes. This is really confusing.

However, if I turn off the wifi first, then search, then turn on the wifi and search, then turn off the wifi, an "The Internet connection appears to be offline." error would appear. 

The same problem happens when I load request in web view. When the wifi is turned off, the web view just keeps loading request and never stops. I have no idea why.

**Comment by mengwanguc** [comment]
In web view, I used 
`func webView(_ webView: UIWebView, didFailLoadWithError error: Error)`

When the wifi is turned off, it only gives an "timeout" alert after 60 seconds.

**Comment by tabinks** [comment]
To test the switch from on/off line is a bit more complicated.  You would need to monitor it and keep track of it yourself.  We can discuss this in class.  Don't forget the you can adjust timeouts in the `URLSession` parameters.

**Comment by mengwanguc** [comment]
All right. But the problem is that, when the wifi is turned off, I don't get an error like "not connected to Internet". I only get "timeout" after 1 minute. This is really confusing.

------------------------------
Adjusting timeouts in URLSession really helps! Thanks a lot!
