### ISSUE TITLE
office hours this week

### ISSUE THREAD

**Issue by ramon-luis** [uchicago-mobi/MPCS51030-2017-Winter-Forum#130]
Hi - do you mind confirming office hour times and locations for this week?  I'm not sure if they've been changing each week or have been constant.  Thanks!

**Comment by susanstevens** [comment]
My office hours will be on Saturday from 10am to noon in Young 106. Same time as usual, slightly different location 🙂

**Comment by hbennett766** [comment]
Mine are Sunday from 3:30-5:30p in Young 106

**Comment by prazgaitis** [comment]
I will be holding mine at the same time as Hannah
