### ISSUE TITLE
Office Hours and Assignment 7 Due Date

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/MPCS51030-2017-Winter-Forum#133]
I have to cancel my office hours for this Thursday.  I will hold office hours before/after class on Monday to make up for them.  I will post the exact time and location later.

To allow time for students to come to office hours for assistance on the assignment 7, it will now be due on **Wednesday, March 1 at 11:59pm**.

**Comment by lakshman111** [comment]
Just a heads up, several students have office hours for Data Analysis after class on Monday nights.
