### ISSUE TITLE
url prefix for JSON image

### ISSUE THREAD

**Issue by ramon-luis** [uchicago-mobi/MPCS51030-2017-Winter-Forum#135]
What is the prefix to process or view images that have been uploaded?

For example, one of my uploaded images has the image_url: `image/ahNzfnN0YWNoZXNhbmRnbGFzc2VzciYLEgRVc2VyIg9yYW1vbmxyb2RyaWd1ZXoMCxIFUGhvdG8YgfEEDA/`

I can't figure out what prefix to use so that I can preview the image in my browser or what prefix to use in order to then process the image in swift.

**Comment by tabinks** [comment]
http://stachesandglasses.appspot.com/image/ahNzfnN0YWNoZXNhbmRnbGFzc2Vzch4LEgRVc2VyIgd0YWJpbmtzDAsSBVBob3RvGPGTCQw/

![](http://stachesandglasses.appspot.com/image/ahNzfnN0YWNoZXNhbmRnbGFzc2Vzch4LEgRVc2VyIgd0YWJpbmtzDAsSBVBob3RvGPGTCQw/)

**Comment by ramon-luis** [comment]
Thanks!

So, if my personal info shows image data, but the image url shows "No Image" when I load it in the browser, I assume something went wrong in my data upload process?

**Comment by ramon-luis** [comment]
I'm still not able to see any image when I use the upload function provided in the playground.  It appears that the image data is not being processed or uploaded correctly.  Is there something missing that we need to implement?

Also, what's the best way to remove JSON data from the web app?  I've got a bunch of bad data loaded from trying to troubleshoot the issue.

**Comment by susanstevens** [comment]
Can you provide more detail about how it isn't working? Are you getting an error in Xcode? Or when you paste the URL into the browser, are you getting a 404? If that's the case, could you tell us what URL you're using? I need a little more info here in order to help you troubleshoot.

I'm not sure about removing images. @tabinks is there any easy way to do this?

**Comment by ramon-luis** [comment]
When I try to view the image in the web browser, the web browser says "No Image"

Here is an example image URL:
https://stachesandglasses.appspot.com/image/ahNzfnN0YWNoZXNhbmRnbGFzc2VzciYLEgRVc2VyIg9yYW1vbmxyb2RyaWd1ZXoMCxIFUGhvdG8Y8eYXDA/

**Comment by susanstevens** [comment]
Hmm... If you want to push your code to your repository I can try to take a look at it today. It sounds like there's an issue with how you are posting images.

**Comment by tabinks** [comment]
@RAM0N-LUIS Did you get this fixed?

**Comment by ramon-luis** [comment]
No - still outstanding.  The JSON on the webapp for my student name (ramonlrodriguez) shows several data for several images, but none of the URLs actually have an image.
