### ISSUE TITLE
Assignment 7 Specification

### ISSUE THREAD

**Issue by alexliu0809** [uchicago-mobi/MPCS51030-2017-Winter-Forum#140]
Hi, I saw on the website that there is tip like this: "Tip: Make sure to adjust the `contentMode` property of the image view in the cell." I wonder what does this mean?

**Comment by susanstevens** [comment]
Take a look at this tutorial: http://useyourloaf.com/blog/stretching-redrawing-and-positioning-with-contentmode/. It explains the different `contentMode` options for images. You'll want to make sure you set your images' content mode in such a way that the images are not stretched or distorted in the collection view cells.

**Comment by tabinks** [comment]
Unless an image is the exact size of the `UIImageView` your image will need to be resized to fit.  Using `contentMode` you control how the resizing will occur (eg. fill aspect, stretch, etc.).
