### ISSUE TITLE
Playground for Collection Views?

### ISSUE THREAD

**Issue by MengchenLiu** [uchicago-mobi/MPCS51030-2017-Winter-Forum#141]
Is there a playground for Collection View? I saw it in slide but didn't find it.

**Comment by tabinks** [comment]
It's there.  Pull the the repo again named Session8 CollectionView.

**Comment by MengchenLiu** [comment]
Is this the right link ?
https://github.com/uchicago-mobi/mpcs51030-2017-winter-playgrounds

**Comment by MengchenLiu** [comment]
Found it, thanks professor!

**Comment by kirinm** [comment]
Where did you find it?

**Comment by MengchenLiu** [comment]
I found it here
https://github.com/uchicago-mobi/MPCS51030-2016-Summer-Playgrounds/tree/master/2016-CollectionView
But this is a project, not a playground.
