### ISSUE TITLE
Uploading Photos

### ISSUE THREAD

**Issue by lakshman111** [uchicago-mobi/MPCS51030-2017-Winter-Forum#144]
I'm trying to use `http://stachesandglasses.appspot.com/` to upload photos to see if I can retrieve them.  However, when I hit "Post", the images are stored to the user "default", not my own.  Is there another way that we can upload pictures to test retrieving them?

**Comment by susanstevens** [comment]
Make sure that the url you use to post your images has your own username at the end: http://stachesandglasses.appspot.com/post/YOUR-UCHICAGO-USERNAME. (And make sure the username you use to post is the same as the username you use to retrieve photos!)

**Comment by tabinks** [comment]
@susanstevens is correct, you need to change the URL.
