### ISSUE TITLE
NSDocumentsDirectory Resources

### ISSUE THREAD

**Issue by hbennett766** [uchicago-mobi/MPCS51030-2017-Winter-Forum#145]
Here's how to get reference to the user's documents directory (also in lecture slides):

https://www.hackingwithswift.com/example-code/system/how-to-find-the-users-documents-directory

And here's a helpful resource for saving files to directories. Note, this is saving an image to the directory, whereas you'll be saving the cache you create.

https://iosdevcenters.blogspot.com/2016/04/save-and-get-image-from-document.html

**Comment by mengwanguc** [comment]
By " you'll be saving the cache you create.", does it mean that we need to save the NSCache in Documents?
