### ISSUE TITLE
When should we make new request for latest json version after the very first request?

### ISSUE THREAD

**Issue by MengchenLiu** [uchicago-mobi/MPCS51030-2017-Winter-Forum#149]
The requirments say "Store the data feed as a file in the Documents directory after successfully downloading it from the server. This should be updated whenever a successful request is made. The collection view should always attempt to load the data from the cached file on disk first before going to the server for the latest version."

So after collection view load the data from disk , does it need to make a new request to server immediately? Or it just need to refresh after user upload some new images?

**Comment by tabinks** [comment]
Refresh after new upload.

**Comment by MengchenLiu** [comment]
I see, thanks professor.
