### ISSUE TITLE
Final Project Repository

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/MPCS51030-2017-Winter-Forum#150]
https://classroom.github.com/assignment-invitations/fcd9266ca8c803586c35bd925fd79d51

If you have a partnership, please email me so I can add an additional user to one of the repositories.

**Comment by alexliu0809** [comment]
Hi, Benyan Gong (bygong@uchicago.edu) and Alex Liu (alexliu0809@uchicago.edu) are working on the same project. Thanks.

**Comment by dczmydc** [comment]
Hi,
Xinghan Zhang(zxh@uchicago.edu, git name=yaoyaozxh) and Mingyuan Zhong (zhongm1@uchicago.edu, git name=dczmydc) are working on the same final project. Thanks.

**Comment by haozeWang** [comment]
Hi,
Haoze Wang(haoze@uchicago.edu, git name=haozeWang) and Meng Wang (wangm12@uchicago.edu, git name=mengwanguc) are working on the same final project. Thanks.

**Comment by fanfanfan94** [comment]
Hi,
Yifan Shao(ivan94@uchicago.edu, git name=ivan1994) and Zhengyang Chang(zhengyangc@uchicago.edu, git name=c439621258) are working on the same final project. Thanks.

**Comment by jam-world** [comment]
My library is too huge to push on to the github. What should I do? @tabinks

**Comment by dczmydc** [comment]
Hi, @tabinks 
I still can not visit my teammate's repository. Could you please add my account to his final repository? His git name is yaoyaozxh.
