### ISSUE TITLE
Delete the files on the web server

### ISSUE THREAD

**Issue by Victoriatheeast** [uchicago-mobi/MPCS51030-2017-Winter-Forum#151]
I uploaded some empty images. How I can delete these images?
Thank you!

**Comment by ramon-luis** [comment]
A workaround I used is to re-upload the photos with a consistent, unique caption (I.e. "validImages") and then parse the JSON to only show images that have that caption.

**Comment by Victoriatheeast** [comment]
Good trick, thank you!

**Comment by tabinks** [comment]
@Victoriatheeast There is no way for you to delete them, but I can.  I will do this for all images after the class is over, but if you really need me to, I can delete them for you.

Also, you can just use a different username when you upload and you'll get a new set.

**Comment by tabinks** [comment]
@RAM0N-LUIS Good idea, too.

**Comment by Victoriatheeast** [comment]
@tabinks Sounds nice. It's fine, just leave it there.
