### ISSUE TITLE
Misplaced Views

### ISSUE THREAD

**Issue by hsuanhsuantsai** [uchicago-mobi/MPCS51030-2017-Winter-Forum#152]
![2017-03-01 12 06 57](https://cloud.githubusercontent.com/assets/17528576/23473965/c4ac8780-fe77-11e6-85ca-18d9201b7ad0.png)

Hi,

I've been stuck in this issue for a long time. The size of my collection view is fixed and I can't modify it. Does anyone know how to solve it?

Thanks.

**Comment by ijl0322** [comment]
I think the issue may be that you're using a CollectionViewController, I think by default that means the collection view will fill up the whole page. If you use a ViewController and put a collection view inside that, it should be okay ?

**Comment by susanstevens** [comment]
I believe @ijl0322 is correct. Good observation.

**Comment by hsuanhsuantsai** [comment]
Oh...but if it is true, why do we need different view controller?

**Comment by susanstevens** [comment]
If you want to be able to change the size of your collection view, you need to use a regular `UIViewController` and drag a collection view inside of it. If you don't want to change the size of your collection view, you can use a `UICollectionViewController`.

**Comment by hsuanhsuantsai** [comment]
Got it.
@susanstevens @ijl0322 Thank you for the help.
