### ISSUE TITLE
Images are populated, but showing blank.

### ISSUE THREAD

**Issue by imweihuang** [uchicago-mobi/MPCS51030-2017-Winter-Forum#153]
Hi, 

It seems like my images are populated and cells in the collection view are created successfully.  I also put the UI work process to the main thread. But when I run the app, the images are not showing and look blank (I can still tap on the cell and go to detail image view).

I have been stuck with this for a while, can someone take a look? The code is in the repo, thanks!

**Comment by mengwanguc** [comment]
Maybe your collection view have finished loading before you successfully download your images. Did you reload the cell data after the image is downloaded?

**Comment by imweihuang** [comment]
That's a good point. But yes, actually I created a delegate so that I can call collection view reload method after the success download in SharedNetworking class.

**Comment by hsuanhsuantsai** [comment]
Does your image show up in the image detail view?

**Comment by imweihuang** [comment]
No it doesn't. I tried to log out the image info when the cell is tapped, and I got following message in screenshot, not sure if "{0,0}" indicates something went wrong with the image cached. 

<img width="616" alt="screen shot 2017-03-01 at 3 00 48 pm" src="https://cloud.githubusercontent.com/assets/24487707/23481095/dfe6507c-fe8f-11e6-9417-5bfd11428b1b.png">

**Comment by hsuanhsuantsai** [comment]
I think maybe what you mean for "It seems like my images are populated and cells in the collection view are created successfully. I also put the UI work process to the main thread." only downloads the json but not the images. 
You have to download the images separately.
Suppose you have an image view in your cell, have you checked there's really an image in it when running the app with break point at that part?

![2017-03-01 3 53 49](https://cloud.githubusercontent.com/assets/17528576/23483172/76df0ec2-fe97-11e6-9aef-03cac0179129.png)

Check the eye-like icon.

**Comment by imweihuang** [comment]
It did download the images, and image info is like "<UIImage: 0x6000000927a0>, **{150, 100}**" right after the successful download. But when I check the image info again in the image view, it became "<UIImage: 0x6000000927a0>, **{0, 0}**". I guess something went wrong when I store the images.

**Comment by hsuanhsuantsai** [comment]
It seems your image isn't put into the image view. Have you check how you store images to NSCache and they are really in it? Maybe you didn't handle the downloaded images well (due to local variable or sth else).

**Comment by susanstevens** [comment]
It looks like @mengwanguc is correct -- your collection view not being reloaded after your images finish downloading. You don't need to use a delegate to tell the collection view to reload. Instead you should use a completion block. Your code should look something like this:

```
// In your Shared Networking class
func downloadImage(urlString: String, completion: (UIImage?, Error?) -> Void) { // ... }

// In your view controller
SharedNetworking.sharedInstance.downloadImage(urlString: "some-string") { image, error in
    // do whatever you need to do with your image
}
```

**Comment by imweihuang** [comment]
I see, thank you all for helping out!

**Comment by ghost** [comment]
I think I have having a similar problem. My images are there; when I click on the cell with the black background it will take me to the detail view and I can see the image, but the images in the collection never show up. Where should I be calling reloadData()? Or is something else the issue? Just pushed

**Comment by susanstevens** [comment]
@annalizhaz There are a few different approaches you can take. The most basic approach is to call reloadData on your collection view after each image loads. (Make sure you are NOT calling it from inside one of your collection view data source methods. This will trigger an infinite loop.)

If you have a lot of images, this will slow down performance. You'll be reloading the entire collection view when all you really need to do is update one cell. To avoid that, you can wait until all of your images have finished downloading before calling `reloadData`. Even better, you can reload one cell at a time as each image downloads by using `reloadItems(at: [IndexPath])`.

For this assignment, though, try to get everything working first. If you have time, you can try to improve performance.

**Comment by uykhokhar** [comment]
I have a similarity issue: 

In my view controller I call a method to download the images for each cell. I can see that the images are not nil; (and as an extra precautionary measure, am printing that out), but when i set the cell image to the newImage, i get "fatal error: unexpectedly found nil while unwrapping an Optional value". I suspect that my code for the downloading works because I was previously able to view the detailView of the image. Could someone have a look; i've been stumped by this bug for some time. (i've pushed my code)

            SharedNetworking.sharedInstance.getImageFromURL(galleryItem: cell.galleryItem!) {(newImage) in
                
                DispatchQueue.main.async {
                    
                    if (newImage == nil){
                        print("dispatchqueue called with nil image")
                    } else {
                        print("newImage is not nil")
                    }
                    
                    self.cache.setObject(newImage, forKey: imageURLNSString)
                    cell.indvImage.image = newImage
                    
                    //turn network activity off
                    UIApplication.shared.isNetworkActivityIndicatorVisible = false
                }
            }

**Comment by mengwanguc** [comment]
@uykhokhar I had got the similar issue. I have no idea why, but I solved it in this way: Instead of setting the cell image to the newImage, I just reload the certain cell. And when loading the cell, the cell will always load image from the cache.

**Comment by susanstevens** [comment]
@uykhokhar It looks like you're downloading the images inside of `func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell`. It's a little unusual to make a service call inside of a function that's meant to update the user interface. Instead, I would recommend downloading each image, saving it to NSCache, and then calling `reloadData(at: [IndexPath])`. This will trigger the collection view data source methods for that particular cell. Then, when you're configuring your cell in `collectionView: _, cellForItemAt indexPath: _)` you can grab the image from the cache (without having to wait for it to download).

**Comment by imweihuang** [comment]
@susanstevens A follow up question, in my downloadImage method, the data task is processed after the completion block. Do you know why this happened? If there is anyway I can have the data task before the completion block? 

```
func downloadImage(_ imageURL: NSString, completion: @escaping (UIImage?) -> Void) {
        var image = UIImage()
        // some code ...
        // task code that processed after completion
        let task = session.dataTask(with: url as URL, completionHandler: { (data, response, error) -> Void in
         // ...
        task.resume()
        completion(image)
    }
```

**Comment by susanstevens** [comment]
@imweihuang You shouldn't be calling `task.resume()` inside the task's completion block. The line `let task = session.dataTask...` instantiates the task, but the task is created in the paused state (i.e., not running). `task.resume()` starts the task, and when the task completes, the completion block gets called.

So what you want is:

```
let task = session.dataTask(with: url as URL, completionHandler: { (data, response, error) in

    // now I'm in the task's completion block 
    // everything in here happens _after_ the task completes
    //...
    completion(image) // make sure this is _inside_ the task's completion handler
}

task.resume() // This is the line where the task gets started
```

Hopefully this will resolve your issue. It can be confusing at first because `task.resume()` appears after the completion block in the code, even it's executed before the completion block is executed. The completion block will never be executed until after the task finishes. That's why it's called a "completion block." :smile:

**Comment by imweihuang** [comment]
@susanstevens It helps, thanks Susan!
