### ISSUE TITLE
http://stachesandglasses.appspot.com Over Quota

### ISSUE THREAD

**Issue by ptnsv** [uchicago-mobi/MPCS51030-2017-Winter-Forum#157]
I am not sure if others are seeing this, but that's what I get when I try to download my photos from the server.

Error
 
Over Quota

This application is temporarily over its serving quota. Please try again later.

**Comment by hbennett766** [comment]
If you ping the server too many times, it does that. Have you been testing your app a bunch? It'll fix itself after a certain time period.

**Comment by ptnsv** [comment]
Yes, I have done a good amount of testing today. Thank you.

**Comment by susanstevens** [comment]
I think too many people are hitting the server at once right now. Sounds like everyone is seeing the same error.

**Comment by c439621258** [comment]
Should our app handle such situation? Actually I found that my app crashes when it can't receive an image from the server. Do we need to make sure that it won't crash?

**Comment by uykhokhar** [comment]
I haven't touched my JSON serialization code but I get: error serializing JSON: Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 1." UserInfo={NSDebugDescription=Invalid value around character 1.}

Is this error related to the quota?

**Comment by nishantbadal** [comment]
I'm getting:
error serializing JSON: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

Same over quota problem.

**Comment by cszc** [comment]
I'm having the same problem. I haven't been able to test my latest developments. Should I just submit what I have?

**Comment by dan-olsn** [comment]
I know now is not the best time to be asking, but would it be possible to make a final commit tomorrow when the server is operating again? I'm fishing the cacheing and like @cszc would like to be able to test it.

**Comment by yangchenhao** [comment]
I'm meeting the same problems and cannot test my project right now to make sure if it can run correctly. Can I commit the project after the server goes well?

**Comment by ramon-luis** [comment]
Graders: FYI - the photos that were properly displaying on the web app directly prior to this error might have been corrupted right before the server crashed... which means our users have no initial images to display when loading apps.  (This occurred for me at least.)
