### ISSUE TITLE
Feedback for Assignment 7

### ISSUE THREAD

**Issue by Victoriatheeast** [uchicago-mobi/MPCS51030-2017-Winter-Forum#165]
Hey,

Just wondering when I can expect to get my feedback for assignment 7.

Thank you!

**Comment by hbennett766** [comment]
The best estimate I can give you overall is "soon." The three TAs rotate who grades which projects each week, so I can only speak for my own set of 12 or so, which you are not in. I just finished up my own finals last night, so with my new found free time, I'll be grading tonight, and tomorrow if need be.

**Comment by Victoriatheeast** [comment]
Sounds good. :) No hurry.
