### ISSUE TITLE
office hours Sunday

### ISSUE THREAD

**Issue by prazgaitis** [uchicago-mobi/MPCS51030-2017-Winter-Forum#171]
I will be holding my office hours from 10am-noon on Sunday at the Gleacher Center (Downtown).

Please let me know if you plan on coming! If there are no replies by Sunday, I will be available via Google Hangouts instead of in-person. 

prazgaitis@uchicago.edu

**Comment by zhuoyuzhu** [comment]
Hey Paul, I'll be coming to your office hour tmr.

**Comment by taburaad** [comment]
Same

**Comment by zhuoyuzhu** [comment]
Hey Paul, I'm here. Which room shall we meet?

**Comment by prazgaitis** [comment]
Hey guys, I'm running a little late. Is the cafeteria open? I was planning on meeting in there

**Comment by zhuoyuzhu** [comment]
No worries, take your time. I'm sitting inside the cafeteria
