### ISSUE TITLE
Restrict the app to a device

### ISSUE THREAD

**Issue by mengwanguc** [uchicago-mobi/MPCS51030-2017-Winter-Forum#179]
Hi professor, can we restrict our app to some device only? It may be somewhat difficult for my app to make appropriate adaptive layout. So is it acceptable to restrict my app to, e.g. my iPhone 7?

If yes, how can I make the restriction setting? I find I can only restrict the device orientation to Portrait. Thanks!

**Comment by susanstevens** [comment]
You can restrict an app to iPhone only or iPad only, but not to a specific device size. Ideally your app would work for all iPhones. However, I don't think we'll be deducting tons of points if the device doesn't display perfectly on all screen sizes.
