### ISSUE TITLE
Xcode unexpectedly quitting

### ISSUE THREAD

**Issue by jahnagoldman** [uchicago-mobi/MPCS51030-2017-Winter-Forum#18]
Hi! 

I started to go into the part of the tutorial where you create an About screen (though I know this part is not required) and when I try to copy-paste the text from the tutorial into a textview in Interface Builder, Xcode unexpectedly quits and brings up a problem report. If I instead try and manually type the text and try to insert new line by typing alt-Enter, it also quits. Does anyone know why this might be happening? I can work around it for now (using the Attributes Inspector) / I know this part of the tutorial isn't required, but I was wondering if anyone knows why this might be happening, for future reference? I haven't had any other issues with Xcode quitting until doing this.

Thanks!

**Comment by susanstevens** [comment]
Hmm... I'm not sure why that would be happening. Storyboards can be a little finicky. Are you typing directly into the textview on the storyboard (like the tutorial suggests)? If so, you could try going into the Attributes Inspector in the left panel (the fourth tab) and typing the text there instead.

**Comment by jahnagoldman** [comment]
Yeah, it's only happening when I type directly into the textview on the storyboard. The problem doesn't seem to be happening when I use the Attributes Inspector, so maybe I'll just stick to that. Thank you!

**Comment by ramon-luis** [comment]
I had the same issue and had to use Attributes Inspector to get around it.

**Comment by tabinks** [comment]
I agree with @susanstevens that the storyboard can be a bit finicky sometimes.  If you can continually reproduce this error than it may be worth filing a bug report with Apple.

**Comment by tabinks** [comment]
@jahnagoldman @RAM0N-LUIS Can you commit you code where you had the problem and push to github.  We'll try to figure out what the issue is.

**Comment by jahnagoldman** [comment]
I committed and pushed my final code for the tutorial (Assignment 2) where I did the work-around -- I created a textview and entered text into it the Attributes Inspector. Is that what you mean or is there something else we should commit?

**Comment by susanstevens** [comment]
Yep! I downloaded your project, and I'm also seeing the crash when I hit Option+Enter directly in the text view (not in the Attributes Inspector). It doesn't look like there's anything unusual about your text view, so I would assume this is an Xcode bug. Since you can work around it by using the Attributes Inspector, I wouldn't worry about it too much.
