### ISSUE TITLE
The splash screen shows up in the simulator but not on  the device

### ISSUE THREAD

**Issue by Victoriatheeast** [uchicago-mobi/MPCS51030-2017-Winter-Forum#183]
Hey,

The splash screen does not show up on the device, but it works fine in the simulator. 
Does anyone know how to fix it?

Thanks

**Comment by zhuoyuzhu** [comment]
I also had the same issue.
(Update: Just fix this issue)

**Comment by hbennett766** [comment]
Is it possible that your app is just launching too fast to see the splash screen? Try setting a breakpoint at the beginning of app delegate's didFinishLaunching method. Does it pause on the splash screen?

**Comment by Victoriatheeast** [comment]
@hbennett766 Yes, it pauses on the splash screen. I also try using sleep, and it just displays an empty screen on my device.

**Comment by hbennett766** [comment]
Can you push your project to github? I'll take a look at your code.

**Comment by Victoriatheeast** [comment]
Sure. I just pushed it. Thank you!

**Comment by hbennett766** [comment]
I'm testing your app right now on an iPhone 6, and the splash screen is working fine for me. What device are you testing on? Nice job on this game by the way...it's addicting!

**Comment by Victoriatheeast** [comment]
Hey! Glad to hear that it works on your device. Mine is iPhone 7. Maybe something is wrong with my hardware. Anyway, Andrew said that just put a note in the README.md. Thank you! Good to know. :)
