### ISSUE TITLE
What's the difference between splash screen and launch screen?

### ISSUE THREAD

**Issue by mengwanguc** [uchicago-mobi/MPCS51030-2017-Winter-Forum#187]
I have searched the Internet and they all told me to implement the splash screen using the launch screen storyboard. But in the final project requirement it says "This is not the same as the Launch Screen that is provided in Storyboard." I failed to get the point. Could anyone give some hints about the difference between them? Thanks!

**Comment by tabinks** [comment]
The launch screen is automatically displayed as part of the launch cycle of an application.  A splash screen will be under your control.  You have to launch and dismiss it.  You will also have the ability to launch it when you want...the launch screen only shows during a launch from not-running state.

They might look the same to the user, but the implementation is different.

**Comment by temitopeakin1** [comment]
i got that information quite right, the difference between a launch screen and a splash screen
