### ISSUE TITLE
Great Presentations😀...Long Night 😴

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/MPCS51030-2017-Winter-Forum#188]
I wanted to let everyone know that the presentations we saw last were truly outstanding.  The other instructors and myself were blown away by what we saw.  

I also wanted to to thank those of you who were able to stay after hours to watch your fellow classmates presentations.  You can tell how excited everyone was to talk about their projects...perhaps a little too excited.  Showing respect for your classmates time and efforts was a true sign of collegiality.  

Thanks again,
Andrew

**Comment by uykhokhar** [comment]
I'm sure I speak on behalf of some of those those had to leave. We are so sorry that some of us couldn't make it. We had another academic obligation that started at 8:30--a professor review session for the final Data Analysis Math exam. 

The presentations were really awesome!

**Comment by tabinks** [comment]
I was aware of the review session.
