### ISSUE TITLE
Alternative to Command Line Commits

### ISSUE THREAD

**Issue by hbennett766** [uchicago-mobi/MPCS51030-2017-Winter-Forum#21]
If you're new to or uncomfortable with command line git commits, Github has this handy little "Upload Files" button that allows you to drag and drop whatever you want to push to your repository, bypassing the need for the command line. For the long term though, my best real-world advice is to learn and get comfortable with command line git!

![uploadfiles](https://cloud.githubusercontent.com/assets/10427644/22186075/b469dcf4-e0b5-11e6-849d-73683fdaf84e.png)

![uploadfiles2](https://cloud.githubusercontent.com/assets/10427644/22186132/7dcbf26c-e0b6-11e6-982f-22b7ddf11e41.png)

**Comment by dan-olsn** [comment]
They also have a desktop app that provides a GUI for setting up repositories, making commits and syncing. The app provides a tutorial that includes a good explanation of the concept of Git and how to use the app.

https://desktop.github.com/

**Comment by Victoriatheeast** [comment]
Good note! But the dragging and dropping does not work for me it keeps saying something went wrong.

**Comment by hbennett766** [comment]
I've seen that error pop up before, it seems like a Github issue. I have yet to find a client-side solution. If you're having trouble committing to your repository, stop in before class or at office hours!

**Comment by Victoriatheeast** [comment]
I managed to commit using command line though, just wondering why it doesn't work.
