### ISSUE TITLE
Where to Commit HW2 Files

### ISSUE THREAD

**Issue by hbennett766** [uchicago-mobi/MPCS51030-2017-Winter-Forum#23]
There have been a couple cases thus far of submitting assignment 2 to the assignment 1 repository. Make sure you've [accepted the new assignment off the forum](https://github.com/uchicago-mobi/MPCS51030-2017-Winter-Forum/issues/14), and are committing the bullseye project to week 2, and not week 1. There's a new repository for each assignment.

**Comment by turabhassan89** [comment]
Hi,

I just saw this and I believe that I submitted mine in the first week folder as well.

**Comment by susanstevens** [comment]
@turabhassan89 No worries -- we'll pull down your HW 1 repo when we grade the second assignment. Thanks for letting us know!
