### ISSUE TITLE
Learn to Code iOS Apps Tutorials Point to Same Link

### ISSUE THREAD

**Issue by ptnsv** [uchicago-mobi/MPCS51030-2017-Winter-Forum#28]
Hello,

It appears that all of the subsection links in the "Learn to Code iOS Apps with Swift Tutorial from Ray Wenderlich.com" section point to the same link: https://www.raywenderlich.com/143771/swift-tutorial-part-1-expressions-variables-constants

Based on the names, it appears that they were supposed to be different tutorials.

**Comment by susanstevens** [comment]
You're right. For some reason it looks like those links are all redirecting to the first tutorial. Here are links to the second and third parts of that tutorial. It doesn't look like the fourth and fifth parts have been updated for Swift 3 at this point.

[Part 2: Types and Operations](https://www.raywenderlich.com/143885/swift-tutorial-part-2-types-operations)
[Part 3: Flow Control](https://www.raywenderlich.com/143970/swift-tutorial-part-3-flow-control)

**Comment by tabinks** [comment]
Thanks.
