### ISSUE TITLE
Size Classes/Use Trait Variations

### ISSUE THREAD

**Issue by jahnagoldman** [uchicago-mobi/MPCS51030-2017-Winter-Forum#32]
Hi! I see that the homework assignment indicates to turn off Size Classes (as well as Auto Layout) but noticed I don't have the Size Classes box. It seems like it's been changed in XCode 8 to "Use Trait Variations". http://stackoverflow.com/questions/38631327/adaptive-layout-in-xcode-8

Just wanted to clarify / point out in case it needs to be changed on the assignment, or if there's anything I'm missing. Thanks!

**Comment by susanstevens** [comment]
You're right! Storyboards changed in Xcode 8 and the box is now called "Use Trait Variations".

**Comment by tabinks** [comment]
Sorry, I can't keep up with all these changes.  I'll update the write-up.

**Comment by tabinks** [comment]
Updated!
