### ISSUE TITLE
Label Height/Pig Screenshot

### ISSUE THREAD

**Issue by ptnsv** [uchicago-mobi/MPCS51030-2017-Winter-Forum#33]
Hello,

1. The assignment says that we should set the label height to 167px. From the geometry slide, it appears that for iPhone 6, 1pt = 2px. Should that be 167pt or am I missing something? That would make sense because then we have the rest of the 500pt for the slide view.

2. Consider the pig screenshot. 
![image](https://cloud.githubusercontent.com/assets/3254545/22361876/a68d578e-e423-11e6-8ceb-280ccb877304.png)

Are we supposed to have another label on top of the screen or is that "Pig" coming from an image or image view title/text possibly?

Thank you.

**Comment by prazgaitis** [comment]
yep, You can use 167 pt. My size inspector looks like this:

![screen shot 2017-01-27 at 7 12 19 am](https://cloud.githubusercontent.com/assets/5226246/22371993/15d99800-e460-11e6-9c77-6135dc50f6fe.png)
