### ISSUE TITLE
Playing Sounds in Swift 3.0

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/MPCS51030-2017-Winter-Forum#34]
Since the link in the assignment write-up to the tutorial on playing sounds appears to be broken, here is another [short tutorial on playing sounds](https://www.hackingwithswift.com/example-code/media/how-to-play-sounds-using-avaudioplayer).

You can drag and drop your sound effects directly into your project navigator (at the same level as your view controller and storyboard files). Make sure to check "Copy if needed" in the dialogue box that pops up -- otherwise your sound files will NOT be included in your repo!

**Comment by bygong** [comment]
Hi, I wonder why should we use a URL for sound files? Is there a way we can do like we do on images? 

If use URL, is there anything like a path relative to the working space? Otherwise how to make it play on a target machine?

**Comment by bygong** [comment]
Ah I see what it means. I just thought that the assignment wants us to pass the paths of sound files directly into it.

**Comment by Victoriatheeast** [comment]
Thank you for the tutorial! But I found trouble playing the app's sound on my Iphone. Any tricks?

**Comment by hbennett766** [comment]
Can you commit your project to github so we can take a look?

**Comment by Victoriatheeast** [comment]
Yes, I just did it.

**Comment by hbennett766** [comment]
There's no .xcodeproj file, which is what's needed to run the app. Can you commit the entire project folder? It should include the project file as well as the folder that's currently committed.

**Comment by Victoriatheeast** [comment]
Sorry, since the project file name is the same as the folder name. Just did it.

**Comment by hbennett766** [comment]
Your sounds work for me, I'm running on the simulator

**Comment by Victoriatheeast** [comment]
I know, but it doesn't work on my IPhone.

**Comment by tabinks** [comment]
Check that the sound file is included in the bundle.  If you are referencing a file on your Mac, it will play in the simulator, but not on device.

**Comment by Victoriatheeast** [comment]
Do you mean if they are included in the Copy Bundle Resources?

**Comment by tabinks** [comment]
@Victoriatheeast Yes.  They should be in included in the bundle.

**Comment by tabinks** [comment]
The other thing to look at would be in the sound files are in the correct format.  iOS can be a bit picky about the settings on a sound file, even if the format is correct.  Take a look at this article: https://www.raywenderlich.com/69365/audio-tutorial-ios-file-data-formats-2014-edition

**Comment by hbennett766** [comment]
I got them to play on a device. The files weren't in the main bundle. Try removing your mp3s and re-dragging them to your project. It'll bring up a drop-down menu, and just make sure "Copy items if needed" is checked, and "Create folder references" is selected.

**Comment by turabhassan89** [comment]
Should the sound immediately stop playing when the OK is tapped on the alert? If Yes, how to go about it ?

**Comment by tabinks** [comment]
For this assignment, it's ok to let them play out.  To do this correctly, you would probably use a different framework that gives you more control over the sound playback.

**Comment by tabinks** [comment]
Thanks @hbennett766

**Comment by Victoriatheeast** [comment]
@tabinks Yes, it is included. @hbennett766 I removed and dragged back again, but still it didn't work, and I got warnings regarding the dependencies of the mp3 files. I am gonna look into it.

**Comment by Victoriatheeast** [comment]
It works now. Thank you both! :)
