### ISSUE TITLE
aqme Console Messages

### ISSUE THREAD

**Issue by ptnsv** [uchicago-mobi/MPCS51030-2017-Winter-Forum#37]
Hello,

Once my app plays a sound, the following messages keep on coming in the console:

2017-01-28 21:44:53.939029 It's A Zoo in There[1937:50520] [aqme] 255: AQDefaultDevice (173): skipping input stream 0 0 0x0
2017-01-28 21:44:55.947636 It's A Zoo in There[1937:50520] [aqme] 255: AQDefaultDevice (173): skipping input stream 0 0 0x0

Does this indicate anything bad that we need to handle?

Thank you.

**Comment by ramon-luis** [comment]
I have same issue.  This thread seems to imply its a logging error that we can ignore:
http://stackoverflow.com/questions/40389308/strange-aqdefaultdevice-logging

Can an instructor confirm that we can ignore it?

**Comment by tabinks** [comment]
Yes, you can ignore it.  

There are some frameworks that will throw some odd log messages when running on the simulator.  You will probably notice that if you put it on a device than you won't see those messages.
