### ISSUE TITLE
Case Study Sign-up

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/MPCS51030-2017-Winter-Forum#41]
Please fill this form out ASAP: https://goo.gl/forms/vexksWl3TVgjMjwW2

**Comment by bygong** [comment]
Hi Professor, can we study on a Chinese app? I do know some nice works there.

**Comment by tabinks** [comment]
是

**Comment by bygong** [comment]
Haha funny! We usually say "可以“ as "yes", "不可以” or “不行” as "no" when somebody ask for permission. Thanks!

**Comment by tabinks** [comment]
I tried.
