### ISSUE TITLE
Looking for a Teammate!

### ISSUE THREAD

**Issue by giannich** [uchicago-mobi/MPCS51030-2017-Winter-Forum#44]
I am looking for a teammate so that we can partner up for the case study project! I got a couple of apps in mind that we can present, but I'm open to anything!

**Comment by imweihuang** [comment]
Hi, I'm interested! You can reach me at weihuang@uchicago.edu

**Comment by giannich** [comment]
Thanks Wei, I just sent you an email.

**Comment by bgharper** [comment]
If anyone is still looking, I could use one as well! I'm open to suggestions, my email is billgharper@gmail.com

**Comment by rstein85** [comment]
I'm also looking for a partner. I'm open to any app. My email is Steinbach.ryan@gmail.com.

**Comment by cszc** [comment]
Also looking for a partner. Happy to do it whenever - Monday is fine. I'm just not here during the make-up session. Open to any app. cszchung@gmail.com

**Comment by tabinks** [comment]
@cszc @rstein85 Want to partner up for Monday?

**Comment by cszc** [comment]
@rstein85 @tabinks I would do that

**Comment by tabinks** [comment]
@cszc I put you on the schedule for Monday.  I will post one more time about partners.  Reach out to anyone in the list.

**Comment by cszc** [comment]
will do, thanks

**Comment by rstein85** [comment]
@cszc @tabinks works for me!
