### ISSUE TITLE
Enable Refreshing in TableViewController

### ISSUE THREAD

**Issue by ijl0322** [uchicago-mobi/MPCS51030-2017-Winter-Forum#46]
Today at office hour we found out that Xcode automatically disables refreshing when you add a new TableViewController. 

To enable refreshing, use the following code: 

self.refreshControl = UIRefreshControl()

or go to mainStoryBoard > select your TableViewController > select Simulated Metrics on the side bar > change Refreshing to Enable (it's set to Disabled at first)

Hope this helps anyone who's running into the same problem! 
<img width="261" alt="screen shot 2017-02-02 at 3 19 17 pm" src="https://cloud.githubusercontent.com/assets/15901531/22568863/0517930a-e95b-11e6-93cd-78607afb8faa.png">

**Comment by tabinks** [comment]
This one stumped me too.  It's new a "feature" in Xcode 8.

**Comment by ijl0322** [comment]
Sorry guys, I've been trying to test why my Pull to refresh wasn't working after I changed something in my code xD
