### ISSUE TITLE
Case Study Deadline Tomorrow at Noon; Need Volunteers for this Week

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/MPCS51030-2017-Winter-Forum#47]
Please fill out the case study form in #41.  If you do not I will assign you a time!!  

So far we have no one signed up for this week.  We need to have people go every week for the rest of the quarter, so please consider going this upcoming week.  If I don't get any volunteers, I will be assigning it to groups randomly.

**Comment by tabinks** [comment]
Also, there is someone looking for a partner in #44.

**Comment by mengwanguc** [comment]
Hi professor, I have not decided which app to study on. Can I leave the Application Name as "Not Decided"? Or can I fill it with some application name, and later change to another one? Thanks!

**Comment by tabinks** [comment]
Yes, that is fine.
