### ISSUE TITLE
Last Call for Presenting this Week Before I Randomly Choose

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/MPCS51030-2017-Winter-Forum#48]
The homework will get increasingly more time consuming through the rest of quarter.  It's better to get this over with quickly.

**Comment by ptnsv** [comment]
I can present on Monday, but I don't have a teammate yet. If we have an odd number of students, can I present by myself?

**Comment by tabinks** [comment]
@ptnsv There are other students looking for partners.  See #47 and #44.

**Comment by tabinks** [comment]
@ptnsv, @zhuoyuzhu, @nishantbadal We have an odd number.  From what it looks like, you all can form one group IF you agree to present this Week.

**Comment by zhuoyuzhu** [comment]
@tabinks Hi Professor, I've got a project deadline this Sun and another mid-term exam next Wed so I probably won't be able to do this presentation this week.

**Comment by tabinks** [comment]
@zhuoyuzhu Ok.  I won't schedule you this Monday.  Look at #49 and coordinate a partner and pick an open week (7,9 or 10).
