### ISSUE TITLE
Presentation Schedule

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/MPCS51030-2017-Winter-Forum#49]
## Week6 (February 6th)
* Ashwin Aggarwal, Giacomo Glotzer	(DarkSky)
* Christine Chung, @rstein85 (?)
* @ptnsv, @uykhokhar (?)

## Week7 (February 13th)
* Xin Wen, Yi Wang (UChicago)
* Gianni Chen, Wei Huang	(Robinhood)
* Bill and Ramon (DuoLingo)

## Make-up Class (February 18)
* Jahna Goldman, Isabel Lee (Etsy)
* Mengchen Liu, Flora Tsai	(Twitch)
* Zhengyang Chang, Yifan Shao	(forest)

## Week 8 (February 20)
* Yan Cui, Chenhao Yang	(Venmo)
* Xinghan Zhang	Mingyuan Zhong (News)
* Alex Enze Liu, Benyan Gong (Taskcode)

## Week 9 (February 27)
* Anqi Wu, Kirin Masood	(Tinder)
* Lakshman Mody, Tony Aburaad	 (Slack)
* @nishantbadal, @zhuoyuzhu (?)

## Week 10 (March 6)
* Haoze Wang, Meng Wang (Shanbay words)
* Turab Hassan	Anna Hazard	(Snap Chat)

**Comment by tabinks** [comment]
From what I can see, here are the singles.  Please make arrangements with each other and fill in the weeks that only have 2 presentations.
@cszc, @rstein85, @bgharper, @ptnsv, @zhuoyuzhu, @nishantbadal

**Comment by zhuoyuzhu** [comment]
Hey, I have an app idea about video social network. If you @cszc, @rstein85, @bgharper, @ptnsv, @nishantbadal are interested, please reach out to me by zhuoyuzhu@uchicago.edu. I am also open to other proposals.

**Comment by ptnsv** [comment]
I could go on Monday as well. Christine Chung (assuming @cszc), are you interested in presenting together? I have one app in mind, but am also open to other apps. Thank you.

**Comment by cszc** [comment]
@ptnsv sorry, @rstein85 and I have already teamed up!

**Comment by ptnsv** [comment]
@cszc, no problem, thanks for letting me know.

I know that @zhuoyuzhu cannot present on Monday. Would anyone else like to present on Monday?

**Comment by uykhokhar** [comment]
@ptnsv, I'm available for monday. ukhokhar@uchicago.edu

**Comment by tabinks** [comment]
@ptnsv @rstein85 @zhuoyuzhu @cszc @nishantbadal @bgharper  I can't follow exactly what going on here.  Can you email me the partnerships and day you are presenting.

**Comment by ptnsv** [comment]
Umar and I will present info about Wunderlist on Monday. Please add us to that third Monday spot.

**Comment by cszc** [comment]
Ryan Steinbach @rstein85 and I are presenting Yelp on Monday

**Comment by nishantbadal** [comment]
@bgharper @ptnsv  @zhuoyuzhu I can't present this Monday, but any other week works for me. Please let me know if any of you are still free.

**Comment by nishantbadal** [comment]
@zhuoyuzhu and I have teamed up.

**Comment by zhuoyuzhu** [comment]
@tabinks Hi Professor, @nishantbadal and I've decided to present on week 9.

**Comment by bgharper** [comment]
Who is left? If I'm the odd person out I could do it the last week, the person I was talking to seems to have partnered up because he hasn't responded

**Comment by jam-world** [comment]
Is there still a team open now? Or I can present on my own? @tabinks

**Comment by dan-olsn** [comment]
@jam-world, I can pair with you. I was going to say [Sky Guide](https://itunes.apple.com/us/app/sky-guide-view-stars-night/id576588894?mt=8), but if you have something else that is fine too. Looks like we'll be Week 10. You can email me danolsen@uchicago.edu
