### ISSUE TITLE
IssueTableViewController - showing up outside main folder

### ISSUE THREAD

**Issue by jahnagoldman** [uchicago-mobi/MPCS51030-2017-Winter-Forum#50]
Hi! I have a question about my homework 4 assignment that I've pushed to my homework 4 repo:

For some reason, on the github repo page (and in the file folder on my computer), my "IssueTableViewController.swift" file shows up entirely outside of the two main folders there normally are in an XCode project. However, when I download it/open it up in XCode, it shows up as normal, inside of the main folder where all the other Swift files are, and the project seems to be working fine. I was wondering if anyone could confirm the project should still work fine, e.g. when you download it to grade it? Also, if you know why this might be happening, or if it's normal for certain cases?

Thanks so much!

**Comment by susanstevens** [comment]
If you're able to run the project when you download the zipped project from GitHub, then you should be fine! The structure of the project navigator (i.e., the left panel in Xcode where it shows your files) doesn't necessarily match the file structure (i.e., what you see in Finder). When you create a new file in Xcode, it'll ask you where you want to save the file, so you might have accidentally saved it outside of usual folder.

If you want, you can open your project in Finder and drag that file into the main folder. You'll notice that the file name will then appear in red in the project navigator, which is Xcode's way of telling you it can't find the file. Just drag the file from Finder into the project navigator in Xcode and all should be well again. (Just to be safe, after you commit & push to your repo, I would still download the zipped project or clone a new repo and double-check that everything is working OK.)

For really big projects where the project navigator is totally different from the file structure in Finder, there's [this awesome tool called synx](https://github.com/venmo/synx) that rectifies the situation.

**Comment by jahnagoldman** [comment]
Okay great - thanks so much!!
