### ISSUE TITLE
GitHub API Paging

### ISSUE THREAD

**Issue by rstein85** [uchicago-mobi/MPCS51030-2017-Winter-Forum#52]
Howdy friends,
Doing the homework today I noticed my 'total issues' count was always returning 30 while the real number is 50+. I did some digging and found the GitHub API uses paging to limit the amount of data returned in each request. If the page parameter isn't specified in the request the first page is returned by default. 

For example,
Returns the 30 most recent issues:
https://api.github.com/repos/uchicago-mobi/mpcs51030-2017-winter-forum/issues?state=all&page=1

Returns the next 20+ issues:
https://api.github.com/repos/uchicago-mobi/mpcs51030-2017-winter-forum/issues?state=all&page=2

Makes coding a little trickier to handle multiple API requests.

**Comment by tabinks** [comment]
@rstein85 is correct that GitHub limits the returned results to 30.  If you want you can request more using the `per_page` parameter.  However, **for this assignment using the 30 results is fine.  You do not have use paging to get all the results.**
