### ISSUE TITLE
Function not triggering

### ISSUE THREAD

**Issue by turabhassan89** [uchicago-mobi/MPCS51030-2017-Winter-Forum#56]
In my issues IssuesTableViewController I have the download data function inside the view did load function but my function to create cells gets called first therefore returns empty. After that my downloadData function runs and downloads the data just fine

**Comment by turabhassan89** [comment]
So I figured that my downloading function hasnt finished and it is moving on to the next tasks. How do I make it wait so that the downloading function has finished first?

**Comment by hbennett766** [comment]
The table view delegate methods (numberOfRowsInSection, cellForRowAtIndexPath, etc) get called before viewDidLoad, so you're right, as-is, the data will always download after the table view populates. You'll have to create a completion block/handler for your data download, which when done, will call back and say "hey I'm done getting the JSON", and you use the inside of that block to reload your table view.

**Comment by turabhassan89** [comment]
I have the tableView.reloadData() function in my completionHandler function but my table only gets populated when I pull the table down and not in the initial view, even though the data gets downloaded and delegate methods are called

**Comment by hbennett766** [comment]
I just downloaded and ran your app, and table population in IssueTableViewController works fine. There was jus a 5-10 sec delay on the tableView reloading itself. Is that what you're seeing?

**Comment by turabhassan89** [comment]
Yes! that's the issue ! i was not waiting long enough  and was worrying for no reason !
