### ISSUE TITLE
Reuse Identifiers

### ISSUE THREAD

**Issue by ghost** [uchicago-mobi/MPCS51030-2017-Winter-Forum#57]
I keep getting the error "Prototype Cells must have reuse identifier" in storyboard. Is this related to the hint "Tip: Remember to set the cell identifier's name of the Scene in Storyboard's Identity Inspector"? How can I get it to go away?

I set the "Identifier" field of the table view cell, but that did not work. Also, I am unclear about what this tip means. What is the "cell identifier's name of the Scene?" There are many fields that refer to an "ID" or "identifier" so I'm unsure which field needs to be set for which entity.

**Comment by ijl0322** [comment]
Here are two links that I found very useful on this topic.
In both links there a line like this 
let cell:MyCustomCell = self.tableView.dequeueReusableCell(withIdentifier: cellReuseIdentifier) as! MyCustomCell

That has to be in your code after you set the identifier field of the table view cell. The identifier should match the cellReuseIdentifier you have in your code.  Hope they help!

http://stackoverflow.com/questions/24170922/creating-custom-tableview-cells-in-swift
https://www.youtube.com/watch?v=5lH5fSuDVxg

**Comment by hbennett766** [comment]
The "Other IB Settings" section in the stackoverflow link shows the place in storyboard that the reuse identifier needs to be set. If this doesn't eliminate the warning right away, try running the app, or closing and re-opening Xcode, and re-setting the identifier.
