### ISSUE TITLE
Open URL in safari

### ISSUE THREAD

**Issue by bygong** [uchicago-mobi/MPCS51030-2017-Winter-Forum#58]
Have anyone ran into such situation: When I tried to open the URL when click the button, it execute code like expected but just doesn't do anything. Like the code below, the canOpenURL function returns true, as I step into the "UIApplication.shared.open" function, it just followed by bunch of assembly instructions and quit normally so I can't tell anything from it. Did I miss anything?

`    @IBAction func viewInBrowser(_ sender: Any) {
        print(UIApplication.shared.canOpenURL(segueURL!))
        UIApplication.shared.open(segueURL!)
    }`

**Comment by hsuanhsuantsai** [comment]
Have you hooked @IBAction back to the button?

**Comment by bygong** [comment]
Yes, otherwise the function would not be called either.

**Comment by hsuanhsuantsai** [comment]
canOpenURL only returns a boolean, try UIApplication.shared.open().

**Comment by bygong** [comment]
Uh...I did in the second line, print is just to see why it didn't work. Those code are just little bit messy for some reason.

**Comment by hsuanhsuantsai** [comment]
Uh... sorry, didn't notice that.
But the function works in my case..

**Comment by bygong** [comment]
Ye, so I wonder if it is blocked by iOS itself or sth. Thanks anyway!

**Comment by hsuanhsuantsai** [comment]
Also, my sender is UIBarButtonItem.
Good luck!

**Comment by hbennett766** [comment]
What is the string value of your url? Is there a protocol (http:// or https://)? If that's not included in the url string, the open command will do nothing.

**Comment by bygong** [comment]
It's included, I've tried checked those things said on stackoverflow. If not the canOpenUrl will return false. I think canOpenURL returns true means that I'm able to open it, it's just something stop it from opening. No idea at all...

**Comment by hbennett766** [comment]
Can you commit your project to your week 4 repository? I can download and take a look at it today.

**Comment by bygong** [comment]
Sure, just a minute to finish last part.

**Comment by hbennett766** [comment]
Instead of printing canOpenURL to console, call print(segueURL!). If you look at the string, there's some text (--file:// or something like that) at the end of the URL. Safari won't open this. I hardcoded the true URL string into your call, and it opened as expected. The canOpenURL must be getting fooled by what you're passing in, and going through your check undetected. Check the JSON dictionary for the key value you're getting for this URL. I'm guessing you're using the wrong key. Make sure you grab a URL that's truly only the URL string.

**Comment by bygong** [comment]
Sorry even I hardcoded an URL it still do nothing other than print out true..May I meet an instructor before the class?

<img width="600" alt="screen shot 2017-02-06 at 12 51 19 pm" src="https://cloud.githubusercontent.com/assets/25123629/22661458/07e5650e-ec6b-11e6-9edd-a1d5ed3d8ef4.png">

**Comment by bygong** [comment]
Oh I see where I was wrong. Shouldn't have used the URL constructor with parameter of  fileURLWithPath, sorry for being stupid. Thanks guys!
