### ISSUE TITLE
When to call endRefreshing()?

### ISSUE THREAD

**Issue by lakshman111** [uchicago-mobi/MPCS51030-2017-Winter-Forum#59]
In my refreshTable function, I first repopulate the data (with tableview.reloadData() in the completion block) and then I call endRefreshing...but it seems like the refreshing is ending before data is actually being loaded again.  Can I not call endRefreshing right after repopulating my data?

**Comment by susanstevens** [comment]
Keep in mind that `URLSession` will download the data on a background thread, and execution on the main thread will continue without waiting for the session task to finish. You'll need to call `endRefreshing` _after_ the task completes, i.e., inside of the completion handler (same place you call `tableView.reloadData()`).

Take a look back at the slides on completion handlers (aka closures or blocks). Also, remember that ALL updates to the user interface need to be done on the main thread. (`DispatchQueue.main.async` will get you back on the main thread.)

@turabhassan89 This should help with your question in #56 as well.
