### ISSUE TITLE
Touch bar icon linked to navigator controller disappeared

### ISSUE THREAD

**Issue by c439621258** [uchicago-mobi/MPCS51030-2017-Winter-Forum#61]
At first I set the touch bar controller connect to 3 simple view controller, the touch bar worked well showing three icons. But If I link navigation controller to the touch bar controller, the icorresponding con disappear.

My story board looks like this:

<img width="524" alt="1" src="https://cloud.githubusercontent.com/assets/16811132/22656323/a38b3780-ec58-11e6-8c81-830620394a36.png">

But my APP can't show the icon
![2](https://cloud.githubusercontent.com/assets/16811132/22656443/03cf12d8-ec59-11e6-8534-4bef4a91901f.png)

Any idea how to solve this?

**Comment by prazgaitis** [comment]
You should be able to set the title and image by clicking on the Tab Bar Item (where you want the icon to show up) on the NavigationController, and then use the Attributes inspector to set the Bar Item. 

![screen_shot_2017-02-06_at_10_57_11_am](https://cloud.githubusercontent.com/assets/5226246/22657159/1be275b6-ec5b-11e6-985c-1cb2bbb196d2.png)
