### ISSUE TITLE
issues.count is always 0

### ISSUE THREAD

**Issue by hsuanhsuantsai** [uchicago-mobi/MPCS51030-2017-Winter-Forum#62]
Hi,

I found my issues.count is always 0 in all of the ViewControllers.
It doesn't matter in the first two TableViewControllers.
However, I can't access data from issues in the third ViewController due to this 0 count after doing getIssues function.
Could anyone help me solve this problem?

Thanks.

**Comment by bygong** [comment]
Is the issues your container of issue information? Just FYI once the same came to me and turned out it's I tried to empty the issue list before refreshing data causing some race conditions.

**Comment by hbennett766** [comment]
Can you commit your project so we can take a look?

**Comment by hsuanhsuantsai** [comment]
@bygong I'll try it later. Thank you!
@hbennett766 I've committed it. Thanks.

**Comment by hbennett766** [comment]
You're talking about your circle view controller when you say third view controller, correct? I'm going to continue with that assumption.

The commented-out code you have in viewDidLoad is what's populating the labels with the correct counts. Think about the order in which things are called. Your viewDidLoad method calls getIssues, which fetches all your JSON. While this is happening, viewDidLoad continues working, and populates your label text before the issues are fetched. If you set breakpoints at the end of viewDidLoad, and inside the completion callback for getIssues (where you call tableView.reloadData() in the other controllers), you'll see that viewDidLoad finishes first. Similar to how you re-populate your table views once the JSON is fetched, You have to wait for getIssues to finish and use your completion block callback to signal the labels that they can now set their texts.

**Comment by hsuanhsuantsai** [comment]
Yeah, I know that. I've tried lots of ways to make it wait until the getIssues function is done. However, all failed.

**Comment by hbennett766** [comment]
inside your completion callback, do all the setup code to populate the counts, then to actually set the text for the label, you have to manually grab the main thread.

DispatchQueue.main.async { (set label text here) }

Also, your for loop should end at issues.count - 1. The count starts at 1, but arrays start at index 0, so the current implementation with crash with an out of range error.

**Comment by hbennett766** [comment]
As a general note, any work that updates the UI should be done on the main thread. Otherwise weird "this code looks right, why isn't it working" things happen. I'll be in class in 5, come see me real quick and I can show you in person if it'll help.
