### ISSUE TITLE
Office Hours?

### ISSUE THREAD

**Issue by lakshman111** [uchicago-mobi/MPCS51030-2017-Winter-Forum#65]
On the syllabus, it says that there are office hours today from 3 to 5pm in CSIL 1, but it doesn't look like anyone is there.  Were those office hours moved somewhere else?

**Comment by susanstevens** [comment]
It looks like last year's office hours schedule is showing on the course website for some reason. @tabinks, can you fix that?

We try to post our office hours for each week on github, so I would always take this forum as the source of truth.
