### ISSUE TITLE
UIImageView

### ISSUE THREAD

**Issue by lakshman111** [uchicago-mobi/MPCS51030-2017-Winter-Forum#68]
I am trying to print the UIImages of open and closed on the All-Issues screen.  I am able to print a status label into each cell with the correct status, however an image won't print.  I am setting the image in the below code...please let me know what else I should have set to make an image print besides hooking this up to an outlet in my cell-class:

if issues[indexPath.row].status.contains("open"){
                cell.imageIcon = UIImageView(image: #imageLiteral(resourceName: "FrogFace-50.png"));
                print("The open Image Here")
            } else{
                cell.imageIcon = UIImageView(image: #imageLiteral(resourceName: "ClosedSign.png"));
                print("The Closed Image here")
            }

**Comment by hbennett766** [comment]
Is this a question of trying to print to console the fact that an image was set, or trying to get your images to populate in the imageViews? If it's just logging, don't worry about it for now.

**Comment by lakshman111** [comment]
Trying to get my images to populate in the imageViews
