### ISSUE TITLE
Question on syntax

### ISSUE THREAD

**Issue by lakshman111** [uchicago-mobi/MPCS51030-2017-Winter-Forum#7]
In the following code, why do you get an error when you don't pass the argument type for person?  But you have to pass the argument type for the other arguments? I'm confused.
```swift
func greet(person: String, day: String, special: String) -> String {
    return "Hello \(person), today is \(day) and we will be serving \(special)."
}

greet("Bob", day: "Tuesday", special: "cheese")
```

**Comment by tabinks** [comment]
You need to add the first argument name when you call the function.

```swift
greet(person: "Bob", day: "Tuesday", special: "cheese")
```

**Comment by hbennett766** [comment]
Excluding the first parameter's argument type was allowed in Swift 2, but not in Swift 3.

http://stackoverflow.com/questions/38343497/swift-3-first-parameter-names

**Comment by lakshman111** [comment]
Thanks! Just realized I still have Swift 2 installed...

**Comment by tabinks** [comment]
That was an easy fix.
