### ISSUE TITLE
Slides for yesterday's lecture? 

### ISSUE THREAD

**Issue by ijl0322** [uchicago-mobi/MPCS51030-2017-Winter-Forum#72]
Can we access the slides for yesterday's lecture somewhere ? It looks like the link on the course website isn't working. Thanks!

**Comment by tabinks** [comment]
They're there now..and here: http://uchicago.mobi/sessions/session5/MPCS51030-2017-Winter-Lecture5.pdf

**Comment by tabinks** [comment]
@ijl0322

**Comment by ijl0322** [comment]
Cool. Thanks!
