### ISSUE TITLE
Drag and Drop question

### ISSUE THREAD

**Issue by alexliu0809** [uchicago-mobi/MPCS51030-2017-Winter-Forum#80]
Is it ok that the picture on the bottom (the one at fixed place) disappears after user start dragging and flies back to bottom after stop dragging?

Or it has to stay where it is while dragging as the following image indicates:
![screen shot 2017-02-09 at 10 22 22 pm](https://cloud.githubusercontent.com/assets/8815312/22814085/43b69c80-ef16-11e6-8549-d3239c7047cb.png)

**Comment by tabinks** [comment]
That's fine.
