### ISSUE TITLE
Custom UIView Clarification in Tic-Tac-Toe

### ISSUE THREAD

**Issue by nicholasfasolt** [uchicago-mobi/MPCS51030-2017-Winter-Forum#81]
Just want to make sure I am understanding the assignment instructions completely.

From the demo in class and the screenshots in the assignment write-up it looks like a UIAlertController is being used to display an alert when the game has ended. However, the write-up refers to using a custom UIView. I know we need to create a custom UIView that displays the game rules when the info button is pushed - should we be using a custom UIView to display the game over message, too, or is using an alert OK?

**Comment by tabinks** [comment]
While it does look like a standard `UIAlertViewController` it is actually a custom `UIView`.  You should create your own `UIView` for the assignment and style it however you want.
