### ISSUE TITLE
Passing data between 2 classes

### ISSUE THREAD

**Issue by taburaad** [uchicago-mobi/MPCS51030-2017-Winter-Forum#84]
Hi,

I have my main ViewController class, and my X/O class. The ViewController class gives me current position of my X/O piece on the board as I drag it, and the X/O object itself contains the function telling me when touches ended. I need both of these piece of information to have it snap to an available grid on the board, but they are in different classes. Is there a best way to pass this data from one class to another, or am I approaching this the wrong way?

Thanks

**Comment by susanstevens** [comment]
I wouldn't try to pass data between the two classes. Instead, use the gesture recognizer's `state` property to determine when the user has stopped dragging the piece (i.e., `if recognizer.state == .ended { // snap into place on grid }`).

**Comment by taburaad** [comment]
Thanks!
