### ISSUE TITLE
Gesture Recognizer

### ISSUE THREAD

**Issue by turabhassan89** [uchicago-mobi/MPCS51030-2017-Winter-Forum#85]
I have setup the gesture reconizer for both circle and cross but it seems to be only working for the circle and I cant figure out why.

**Comment by tabinks** [comment]
Conceptually, they should work the same...so it's a bug somewhere.  

Some things to look at:
* Make sure that you have `userInteractionEnabled`
* The gesture recognizer is attached to the correct view

**Comment by turabhassan89** [comment]
I was making one gesture recognizer and then attaching it to both the circle and cross imageviews and it was working only for one. I had to make two separate ones, conceptually what is happening?

This doesnt work:
`      let panGesture = UIPanGestureRecognizer(target: self, action: #selector(handlePan(_:)))
        cross.addGestureRecognizer(panGesture)
        circle.addGestureRecognizer(panGesture)
`
This works:
`
        let panCircleGesture = UIPanGestureRecognizer(target: self, action: #selector(handlePan(_:)))
        let panCrossGesture = UIPanGestureRecognizer(target: self, action: #selector(handlePan(_:)))
        cross.addGestureRecognizer(panCircleGesture)
        circle.addGestureRecognizer(panCrossGesture)
`

**Comment by susanstevens** [comment]
Each gesture recognizer can only be hooked up to one view. When you add the same gesture recognizer to two views, it will be removed from the first view when you add it to the second.

Think about why it would be confusing for the system to apply the same gesture recognizer to multiple views. What would happen when you accessed 'recognizer.view'?
