### ISSUE TITLE
Final Project Form

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/MPCS51030-2017-Winter-Forum#89]
Please fill this out before class on Monday: https://goo.gl/forms/SYesiCmLtiNu4Qx13

This is not final...you can change your mind if you want to.

**Comment by dan-olsn** [comment]
Hi Professor, apologies I was ill and missed last lecture. Is there anything I should know about the requirements for the final beyond what was discussed in the first class? Thank you.

**Comment by tabinks** [comment]
This is just to put down your idea for the final project.  We will talk more about it in class.
