### ISSUE TITLE
No Keyboard Populating

### ISSUE THREAD

**Issue by lakshman111** [uchicago-mobi/MPCS51030-2017-Winter-Forum#9]
After finishing "Build a Basic UI", the iOS keyboard populated when I clicked on the textfield.  However, after finishing "Connect the UI to Code", I noticed that the keyboard no longer populates.  I downloaded the example file at the end of "Connect the UI to Code" and that keyboard still populates when the app is run.  

My code matches the example file, so I'm not sure how to fix this.  Anyone else have this problem?

**Comment by hbennett766** [comment]
Are you testing on the simulator or a device?

**Comment by lakshman111** [comment]
simulator

**Comment by hbennett766** [comment]
Try running your version of the app, and when it opens in simulator, manually trigger the keyboard to display by pulling down the "Hardware" menu -> "Keyboard" -> "Toggle Software Keyboard". Type some text in the text field and click "Done" to dismiss the keyboard. Then try triggering the keyboard via your app, by clicking the text field. Sometimes the simulator's keyboard is finicky and  just needs a little prodding. Let me know whether this works!

**Comment by lakshman111** [comment]
Thanks, that worked!
