### ISSUE TITLE
Adding a TextView to a UIView

### ISSUE THREAD

**Issue by lakshman111** [uchicago-mobi/MPCS51030-2017-Winter-Forum#90]
I'm trying to add a UITextView to a UIView in order to create the top half of the UIView congratulating the player.  Similar to slide 144, I can get a UIView to show up and a UITextView to show up, but I can't embed the UITextView in the UIView.  I tried this with:

nameOfUIView.addSubView(nameOfTextView)

However, then no text shows up, even though I am able to print the correct value of the text to the console by printing nameOfTextView.text.  Since the above line seems to not be working, how do you actually add a UITextView to a UIView?

**Comment by prazgaitis** [comment]
Can you see the UITextView in the view hierarchy debugger? This is a good way to debug your views - sometimes it's hiding behind another view or something like that. Also, it could be off screen.
![screen_shot_2017-02-12_at_4_23_12_pm](https://cloud.githubusercontent.com/assets/5226246/22866694/50055432-f140-11e6-91c2-666bd94dddb4.png)

Also, make sure the v in subview is lowercase:

`view.addSubview(textView)`

Happy to take a look at your project if you push it up to Github!

**Comment by susanstevens** [comment]
You might also want to try printing out the frame of your text view. If either the width or height (or both) are zero, it won't render on screen.

I assume you're creating the text view programmatically, in which case you should use the initializer that allows you to specify the view's frame.

**Comment by lakshman111** [comment]
I went with a different implementation that I got to work, but now I'm pretty sure it was that I didn't set the frame!  Thanks!

I'll also have to try the view hierarchy debugger next time.
