### ISSUE TITLE
Wait For Button To Be Tapped

### ISSUE THREAD

**Issue by ptnsv** [uchicago-mobi/MPCS51030-2017-Winter-Forum#91]
Hello,

When I do a custom view end of game report, instead of a UIAlert, my code continues with execution immediately.  It will set up the grid for the next round before the user even tapped the button for new game. What's a good wait to halt execution until user's response?

Thank you.

**Comment by ptnsv** [comment]
My bad, I had left grid clearing code outside of my button tap handlers and that's why it was cleaning stuff up before user interaction.

**Comment by hbennett766** [comment]
Try placing the code for resetting the game inside the handler for your UIAlertAction.

https://developer.apple.com/reference/uikit/uialertaction

**Comment by ptnsv** [comment]
Thank you Hannah for your quick response.
