### ISSUE TITLE
Policy on Attributing Code

### ISSUE THREAD

**Issue by lakshman111** [uchicago-mobi/MPCS51030-2017-Winter-Forum#92]
In order to draw the line on this assignment, I googled how to draw a line and found the addLine function in [this link](http://stackoverflow.com/questions/40556112/how-to-draw-a-line-in-swift-3).  Am I allowed to copy this function as long as I attribute it to where I got it from?

**Comment by susanstevens** [comment]
Yes, that's fine as long as you provide an attribution. You should also make sure that you understand what the code is doing.

**Comment by lakshman111** [comment]
Sounds good, thanks!

**Comment by hsuanhsuantsai** [comment]
Have you got a problem that the line comes above the result view?
