### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by turabhassan89** [uchicago-mobi/MPCS51030-2017-Winter-Forum#94]
For the popup game info animation, i have setup the code to come down from top and then go down once you close it. Once you close it it first has to go down for the animation effect and then go back to the top so that once you click the button again it shows up. Because of this it snaps to the top instead of going down. Here is the code snippet:

`
    @IBAction func closePopUp(_ sender: Any) {
        UIView.animate(withDuration: 1.5, delay: 1.0, options: .curveEaseOut, animations: {
            self.myPopUp.center.y += 2 * self.view.bounds.width
        }, completion: nil)
      myPopUp.center.y -= 4 * view.bounds.width //Putting it back at the top for next pull down
    }
`

**Comment by prazgaitis** [comment]
You have a lot of options here. Here are some things I would try: 

- just delete the popup when it moves off screen. Create a new one from scratch when you need it
- you could set the UIView's hidden property to `true` and move it back to the top, then set `hidden = false` 

If you push your latest update to Github, I'm happy to take a look!

**Comment by turabhassan89** [comment]
Thanks, I fixed it by moving it at back at the top at starting point. Another clarification that i wanted was about the dimensions, when we are moving an object to move to someplace by saying x.center = 500. What does the 500 represent?

**Comment by hbennett766** [comment]
The [center](https://developer.apple.com/reference/uikit/uiview/1622627-center) property of an object is where the center point of the object's frame will appear on the screen. Center is type CGPoint, or (x, y) coordinates. 500 isn't a valid way to set the center. It could be (200, 500), and the center of your object's frame would be placed at that point on the screen. You can also set it to the center of another view. object.center = self.view.center would place your object in the middle of the screen.
